server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: 마리아URL
    driver-class-name: 마리아 DRIVER
    username: 마리아 USER
    password:  마리아 PASSWORD
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO